### PR TITLE
Complete development of doc in 

### PR DESCRIPTION
**Pull request by Ragansu**
Now the github actions only copies codes and not docs and docs rst files and images are here in there repo.

RC

### CODE REVIEW

**Review by ihsaan-ullah — APPROVED** [review]

**Comment by Ragansu** [comment]
I have made changes for it to work with pages from HEP-Challenge repo. please re-review.

**Comment by Ragansu** [comment]
We will merge it after the other PR is merged :

**Comment by Ragansu** [comment]
We will merge this after PR https://github.com/FAIR-Universe/HEP-Challenge/pull/139 is merged

**Review by ihsaan-ullah — APPROVED** [review]
To be tested after the documentation PR is merged. To check if new docs are generated properlt

**Pull request merged**
